backend:
  name: github
  repo: "Alexis14jara/blog"
  branch: main
  auth_type: "oauth"
  oauth_client_id: "Ov23likpSv3mt6bHrsaY"

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "TÃ­tulo", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Contenido", name: "body", widget: "markdown"}
